package com.ytport.demo.entity;
// Generated 2017-5-9 10:43:17 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.ytport.base.entity.IdEntity;

/**
 * DemoArea generated by hbm2java
 */
@Entity
@Table(name="DEMO_AREA")
public class DemoArea  extends IdEntity {

             //城市代码
    private String areaCod;
             //城市名称
    private String areaNam;
             //省份代码
    private String provinceCod;

    public DemoArea() {
    }

	
    public DemoArea(String id, String areaCod, String areaNam, String provinceCod) {
        this.id = id;
        this.areaCod = areaCod;
        this.areaNam = areaNam;
        this.provinceCod = provinceCod;
    }
   

    
    @Column(name="AREA_COD", nullable=false, length=12)
    public String getAreaCod() {
        return this.areaCod;
    }
    
    public void setAreaCod(String areaCod) {
        this.areaCod = areaCod;
    }

    
    @Column(name="AREA_NAM", nullable=false, length=60)
    public String getAreaNam() {
        return this.areaNam;
    }
    
    public void setAreaNam(String areaNam) {
        this.areaNam = areaNam;
    }

    
    @Column(name="PROVINCE_COD", nullable=false, length=12)
    public String getProvinceCod() {
        return this.provinceCod;
    }
    
    public void setProvinceCod(String provinceCod) {
        this.provinceCod = provinceCod;
    }




}


