package com.ytport.demo.entity;
// Generated 2017-5-9 10:43:17 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.ytport.base.entity.IdEntity;

/**
 * DemoProvince generated by hbm2java
 */
@Entity
@Table(name="DEMO_PROVINCE")

public class DemoProvince  extends IdEntity {

             //省份代码
    private String provinceCod;
             //省份名称
    private String provinceNam;

    public DemoProvince() {
    }

	
    public DemoProvince(String id, String provinceCod, String provinceNam) {
        this.id = id;
        this.provinceCod = provinceCod;
        this.provinceNam = provinceNam;
    }
   

    
    @Column(name="PROVINCE_COD", nullable=false, length=12)
    public String getProvinceCod() {
        return this.provinceCod;
    }
    
    public void setProvinceCod(String provinceCod) {
        this.provinceCod = provinceCod;
    }

    
    @Column(name="PROVINCE_NAM", nullable=false, length=64)
    public String getProvinceNam() {
        return this.provinceNam;
    }
    
    public void setProvinceNam(String provinceNam) {
        this.provinceNam = provinceNam;
    }




}


