package com.ytport.demo.entity;
// Generated 2017-5-9 10:43:17 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.ytport.base.entity.IdEntity;

/**
 * DemoCorp generated by hbm2java
 */
@Entity
@Table(name="DEMO_CORP")
public class DemoCorp  extends IdEntity {

             //单位代码
    private String corpCod;
             //单位名称
    private String corpNam;

    public DemoCorp() {
    }

	
    public DemoCorp(String id, String corpCod, String corpNam) {
        this.id = id;
        this.corpCod = corpCod;
        this.corpNam = corpNam;
    }
   

    
    @Column(name="CORP_COD", nullable=false, length=12)
    public String getCorpCod() {
        return this.corpCod;
    }
    
    public void setCorpCod(String corpCod) {
        this.corpCod = corpCod;
    }

    
    @Column(name="CORP_NAM", nullable=false, length=30)
    public String getCorpNam() {
        return this.corpNam;
    }
    
    public void setCorpNam(String corpNam) {
        this.corpNam = corpNam;
    }




}


