package com.ytport.demo.entity;
// Generated 2017-5-9 10:43:17 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.ytport.base.entity.IdEntity;

/**
 * DemoNation generated by hbm2java
 */
@Entity
@Table(name="DEMO_NATION")
public class DemoNation  extends IdEntity {

             //民族代码
    private String nationCod;
             //民族名称
    private String nationNam;

    public DemoNation() {
    }

	
    public DemoNation(String id, String nationCod, String nationNam) {
        this.id = id;
        this.nationCod = nationCod;
        this.nationNam = nationNam;
    }
   

    
    @Column(name="NATION_COD", nullable=false, length=2)
    public String getNationCod() {
        return this.nationCod;
    }
    
    public void setNationCod(String nationCod) {
        this.nationCod = nationCod;
    }

    
    @Column(name="NATION_NAM", nullable=false, length=64)
    public String getNationNam() {
        return this.nationNam;
    }
    
    public void setNationNam(String nationNam) {
        this.nationNam = nationNam;
    }




}


