package com.ytport.demo.entity;
// Generated 2017-5-9 10:43:17 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.ytport.base.entity.IdEntity;
import org.hibernate.annotations.Formula;

/**
 * DemoWorker generated by hbm2java
 */
@Entity
@Table(name="DEMO_WORKER")
public class DemoWorker  extends IdEntity {

             //职工编号
    private String workerNo;
             //职工名称
    private String workerNam;
             //出生日期
    private Date birthDte;
             //性别(1-男 0-女)
    private String sexCod;
             //民族
    private String nationCod;
             //省份代码
    private String provinceCod;
             //地市代码
    private String areaCod;
             //工作单位代码
    private String corpCod;
             //工龄
    private Short serviceNum;
             //基本工资
    private Double baseNum;
             //备注
    private String note;

    public DemoWorker() {
    }

	
    public DemoWorker(String id, String workerNo, String workerNam) {
        this.id = id;
        this.workerNo = workerNo;
        this.workerNam = workerNam;
    }
   

    
    @Column(name="WORKER_NO", nullable=false, length=12)
    public String getWorkerNo() {
        return this.workerNo;
    }
    
    public void setWorkerNo(String workerNo) {
        this.workerNo = workerNo;
    }

    
    @Column(name="WORKER_NAM", nullable=false, length=32)
    public String getWorkerNam() {
        return this.workerNam;
    }
    
    public void setWorkerNam(String workerNam) {
        this.workerNam = workerNam;
    }

    
    @Column(name="BIRTH_DTE", length=7)
    public Date getBirthDte() {
        return this.birthDte;
    }
    
    public void setBirthDte(Date birthDte) {
        this.birthDte = birthDte;
    }

    
    @Column(name="SEX_COD", length=1)
    public String getSexCod() {
        return this.sexCod;
    }
    
    public void setSexCod(String sexCod) {
        this.sexCod = sexCod;
    }

    
    @Column(name="NATION_COD", length=2)
    public String getNationCod() {
        return this.nationCod;
    }
    
    public void setNationCod(String nationCod) {
        this.nationCod = nationCod;
    }

    
    @Column(name="PROVINCE_COD", length=12)
    public String getProvinceCod() {
        return this.provinceCod;
    }
    
    public void setProvinceCod(String provinceCod) {
        this.provinceCod = provinceCod;
    }

    
    @Column(name="AREA_COD", length=12)
    public String getAreaCod() {
        return this.areaCod;
    }
    
    public void setAreaCod(String areaCod) {
        this.areaCod = areaCod;
    }

    
    @Column(name="CORP_COD", length=12)
    public String getCorpCod() {
        return this.corpCod;
    }
    
    public void setCorpCod(String corpCod) {
        this.corpCod = corpCod;
    }

    
    @Column(name="SERVICE_NUM", precision=3, scale=0)
    public Short getServiceNum() {
        return this.serviceNum;
    }
    
    public void setServiceNum(Short serviceNum) {
        this.serviceNum = serviceNum;
    }

    
    @Column(name="BASE_NUM", precision=10)
    public Double getBaseNum() {
        return this.baseNum;
    }
    
    public void setBaseNum(Double baseNum) {
        this.baseNum = baseNum;
    }

    
    @Column(name="NOTE")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }


    private String areaNam;

    @Formula(" (select t.area_nam from DEMO_AREA t where t.area_cod = area_cod) ")
    public String getAreaNam() {
        return areaNam;
    }

    public void setAreaNam(String areaNam) {
        this.areaNam = areaNam;
    }

    private String nationNam;

    @Formula(" (select t.nation_nam from demo_nation t where t.nation_cod = nation_cod) ")
    public String getNationNam() {
        return nationNam;
    }

    public void setNationNam(String nationNam) {
        this.nationNam = nationNam;
    }
}


