package com.ytport.demo.entity;
// Generated 2017-10-22 16:52:38 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.ytport.base.entity.IdEntity;

/**
 * Scode generated by hbm2java
 */
@Entity
@Table(name="SCODE"
    ,schema="EXAM"
)

public class Scode  extends IdEntity {

    private String code;
    private String fldEng;
    private String fldChi;
             
    private String name;
             
    private String defVal;

    public Scode() {
    }
    public Scode(String id,String code,String fldEng) {
        this.id = id;
        this.code = code;
        this.fldEng = fldEng;
    }
    @Column(name="CODE", length=10)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name="FLD_ENG", length=30)
    public String getFldEng() {
        return fldEng;
    }

    public void setFldEng(String fldEng) {
        this.fldEng = fldEng;
    }

    @Column(name="FLD_CHI", length=200)
    public String getFldChi() {
        return this.fldChi;
    }
    
    public void setFldChi(String fldChi) {
        this.fldChi = fldChi;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DEF_VAL", length=20)
    public String getDefVal() {
        return this.defVal;
    }
    
    public void setDefVal(String defVal) {
        this.defVal = defVal;
    }



}


