package com.ytport.demo.entity;
// Generated 2017-10-22 16:44:21 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.ytport.base.entity.IdEntity;

/**
 * WorkerCar generated by hbm2java
 */
@Entity
@Table(name="WORKER_CAR"
    ,schema="EXAM"
)

public class WorkerCar  extends IdEntity {

             //车牌号
    private String carNo;
             //车辆类型
    private String carTyp;
             //使用性质
    private String carUse;
             //车辆所有人
    private String carOwner;
             //购买日期
    private Date buyDte;
             //构成价格(万元)
    private Double carPrice;
             //卖出单位
    private String supplierNam;
             //品牌型号
    private String carBrand;
             //发动机排量
    private String engineDisplacement;
             //邮箱容积(升)
    private String oilVol;
             //整备质量
    private Double carTon;
             //核定载人数
    private Integer personNum;
             //车体颜色
    private String bodyColor;
             //总质量(千克)
    private Double totalWgt;
             //变速箱形式
    private String transmissionForm;
             //是否涡轮增压(0-否 1-是)
    private String turboId;
             //发动机号码
    private String engineNo;
             //保养周期
    private String maintenancePeriod;
             //车辆识别代码
    private String carIdcard;
             //注册登记日期
    private Date regDte;
             //发证日期
    private Date issueDte;
             //年检时间
    private Date partTim;
             //备注
    private String markTxt;
             //联系人电话
    private String linkTel;
             //车主关系
    private String ownerRelation;
             //职工代码
    private String workerCod;
             //职工名称
    private String workerNam;
             //备案单位
    private String corpNam;
             //备案日期
    private Date checkDte;
             //操作人
    private String operMan;
             //操作日期
    private Date operDte;
             //备案类型(0-正式职工 )
    private String checkTyp;
             
    private String addCol1;
             
    private String addCol2;
             
    private String addCol3;
             //是否在用(0-不用 1-在用)
    private String useId;

    public WorkerCar() {
    }

	
    public WorkerCar(String id, String carNo) {
        this.id = id;
        this.carNo = carNo;
    }
   

    
    @Column(name="CAR_NO", nullable=false, length=12)
    public String getCarNo() {
        return this.carNo;
    }
    
    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }

    
    @Column(name="CAR_TYP", length=2)
    public String getCarTyp() {
        return this.carTyp;
    }
    
    public void setCarTyp(String carTyp) {
        this.carTyp = carTyp;
    }

    
    @Column(name="CAR_USE", length=2)
    public String getCarUse() {
        return this.carUse;
    }
    
    public void setCarUse(String carUse) {
        this.carUse = carUse;
    }

    
    @Column(name="CAR_OWNER", length=64)
    public String getCarOwner() {
        return this.carOwner;
    }
    
    public void setCarOwner(String carOwner) {
        this.carOwner = carOwner;
    }

    
    @Column(name="BUY_DTE", length=7)
    public Date getBuyDte() {
        return this.buyDte;
    }
    
    public void setBuyDte(Date buyDte) {
        this.buyDte = buyDte;
    }

    
    @Column(name="CAR_PRICE", precision=12, scale=3)
    public Double getCarPrice() {
        return this.carPrice;
    }
    
    public void setCarPrice(Double carPrice) {
        this.carPrice = carPrice;
    }

    
    @Column(name="SUPPLIER_NAM", length=128)
    public String getSupplierNam() {
        return this.supplierNam;
    }
    
    public void setSupplierNam(String supplierNam) {
        this.supplierNam = supplierNam;
    }

    
    @Column(name="CAR_BRAND", length=64)
    public String getCarBrand() {
        return this.carBrand;
    }
    
    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand;
    }

    
    @Column(name="ENGINE_DISPLACEMENT", length=32)
    public String getEngineDisplacement() {
        return this.engineDisplacement;
    }
    
    public void setEngineDisplacement(String engineDisplacement) {
        this.engineDisplacement = engineDisplacement;
    }

    
    @Column(name="OIL_VOL", length=12)
    public String getOilVol() {
        return this.oilVol;
    }
    
    public void setOilVol(String oilVol) {
        this.oilVol = oilVol;
    }

    
    @Column(name="CAR_TON", precision=12, scale=3)
    public Double getCarTon() {
        return this.carTon;
    }
    
    public void setCarTon(Double carTon) {
        this.carTon = carTon;
    }

    
    @Column(name="PERSON_NUM", precision=5, scale=0)
    public Integer getPersonNum() {
        return this.personNum;
    }
    
    public void setPersonNum(Integer personNum) {
        this.personNum = personNum;
    }

    
    @Column(name="BODY_COLOR", length=32)
    public String getBodyColor() {
        return this.bodyColor;
    }
    
    public void setBodyColor(String bodyColor) {
        this.bodyColor = bodyColor;
    }

    
    @Column(name="TOTAL_WGT", precision=12, scale=3)
    public Double getTotalWgt() {
        return this.totalWgt;
    }
    
    public void setTotalWgt(Double totalWgt) {
        this.totalWgt = totalWgt;
    }

    
    @Column(name="TRANSMISSION_FORM", length=64)
    public String getTransmissionForm() {
        return this.transmissionForm;
    }
    
    public void setTransmissionForm(String transmissionForm) {
        this.transmissionForm = transmissionForm;
    }

    
    @Column(name="TURBO_ID", length=1)
    public String getTurboId() {
        return this.turboId;
    }
    
    public void setTurboId(String turboId) {
        this.turboId = turboId;
    }

    
    @Column(name="ENGINE_NO", length=64)
    public String getEngineNo() {
        return this.engineNo;
    }
    
    public void setEngineNo(String engineNo) {
        this.engineNo = engineNo;
    }

    
    @Column(name="MAINTENANCE_PERIOD", length=32)
    public String getMaintenancePeriod() {
        return this.maintenancePeriod;
    }
    
    public void setMaintenancePeriod(String maintenancePeriod) {
        this.maintenancePeriod = maintenancePeriod;
    }

    
    @Column(name="CAR_IDCARD", length=32)
    public String getCarIdcard() {
        return this.carIdcard;
    }
    
    public void setCarIdcard(String carIdcard) {
        this.carIdcard = carIdcard;
    }

    
    @Column(name="REG_DTE", length=7)
    public Date getRegDte() {
        return this.regDte;
    }
    
    public void setRegDte(Date regDte) {
        this.regDte = regDte;
    }

    
    @Column(name="ISSUE_DTE", length=7)
    public Date getIssueDte() {
        return this.issueDte;
    }
    
    public void setIssueDte(Date issueDte) {
        this.issueDte = issueDte;
    }

    
    @Column(name="PART_TIM", length=7)
    public Date getPartTim() {
        return this.partTim;
    }
    
    public void setPartTim(Date partTim) {
        this.partTim = partTim;
    }

    
    @Column(name="MARK_TXT", length=256)
    public String getMarkTxt() {
        return this.markTxt;
    }
    
    public void setMarkTxt(String markTxt) {
        this.markTxt = markTxt;
    }

    
    @Column(name="LINK_TEL", length=64)
    public String getLinkTel() {
        return this.linkTel;
    }
    
    public void setLinkTel(String linkTel) {
        this.linkTel = linkTel;
    }

    
    @Column(name="OWNER_RELATION", length=64)
    public String getOwnerRelation() {
        return this.ownerRelation;
    }
    
    public void setOwnerRelation(String ownerRelation) {
        this.ownerRelation = ownerRelation;
    }

    
    @Column(name="WORKER_COD", length=20)
    public String getWorkerCod() {
        return this.workerCod;
    }
    
    public void setWorkerCod(String workerCod) {
        this.workerCod = workerCod;
    }

    
    @Column(name="WORKER_NAM", length=20)
    public String getWorkerNam() {
        return this.workerNam;
    }
    
    public void setWorkerNam(String workerNam) {
        this.workerNam = workerNam;
    }

    
    @Column(name="CORP_NAM", length=64)
    public String getCorpNam() {
        return this.corpNam;
    }
    
    public void setCorpNam(String corpNam) {
        this.corpNam = corpNam;
    }

    
    @Column(name="CHECK_DTE", length=7)
    public Date getCheckDte() {
        return this.checkDte;
    }
    
    public void setCheckDte(Date checkDte) {
        this.checkDte = checkDte;
    }

    
    @Column(name="OPER_MAN", length=10)
    public String getOperMan() {
        return this.operMan;
    }
    
    public void setOperMan(String operMan) {
        this.operMan = operMan;
    }

    
    @Column(name="OPER_DTE", length=7)
    public Date getOperDte() {
        return this.operDte;
    }
    
    public void setOperDte(Date operDte) {
        this.operDte = operDte;
    }

    
    @Column(name="CHECK_TYP", length=2)
    public String getCheckTyp() {
        return this.checkTyp;
    }
    
    public void setCheckTyp(String checkTyp) {
        this.checkTyp = checkTyp;
    }

    
    @Column(name="ADD_COL1", length=64)
    public String getAddCol1() {
        return this.addCol1;
    }
    
    public void setAddCol1(String addCol1) {
        this.addCol1 = addCol1;
    }

    
    @Column(name="ADD_COL2", length=64)
    public String getAddCol2() {
        return this.addCol2;
    }
    
    public void setAddCol2(String addCol2) {
        this.addCol2 = addCol2;
    }

    
    @Column(name="ADD_COL3", length=32)
    public String getAddCol3() {
        return this.addCol3;
    }
    
    public void setAddCol3(String addCol3) {
        this.addCol3 = addCol3;
    }

    
    @Column(name="USE_ID", length=1)
    public String getUseId() {
        return this.useId;
    }
    
    public void setUseId(String useId) {
        this.useId = useId;
    }




}


