package com.ytport.demo.entity;
// Generated 2017-10-22 16:44:21 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.ytport.base.entity.IdEntity;
import org.hibernate.annotations.Formula;

/**
 * WorkerRecord generated by hbm2java
 */
@Entity
@Table(name="WORKER_RECORD"
    ,schema="EXAM"
)

public class WorkerRecord  extends IdEntity {

    private String workerCod;
             //姓名
    private String workerNam;
             //参加工作日期
    private Date workDte;
             //单位
    private String corpCod;
             //部门
    private String deptCod;
             //职务
    private String business;
             //毕业学校
    private String gradeSch;
             //专业
    private String speciality;
             //籍贯
    private String homeTown;
             //出生地
    private String birthPlac;
             //到港日期
    private Date toPortTim;
             //上年度收入
    private Double wageNum;
             //健康情况
    private String health;
             //电话
    private String phone;
             //备注
    private String note;
             //缴费基数
    private Double wageBase;
             //工龄
    private Byte serviceNum;
             //贡献值
    private Double contribVal;
             
    private String id;

    public WorkerRecord() {
    }

	
    public WorkerRecord(String id,String workerCod, String workerNam, String corpCod, String deptCod) {
        this.id = id;
        this.workerCod = workerCod;
        this.workerNam = workerNam;
        this.corpCod = corpCod;
        this.deptCod = deptCod;
    }

    public String getWorkerCod() {
        return workerCod;
    }

    @Column(name="WORKER_COD", nullable=false, length=7)
    public void setWorkerCod(String workerCod) {
        this.workerCod = workerCod;
    }

    @Column(name="WORKER_NAM", nullable=false, length=30)
    public String getWorkerNam() {
        return this.workerNam;
    }
    
    public void setWorkerNam(String workerNam) {
        this.workerNam = workerNam;
    }

    
    @Column(name="WORK_DTE", length=7)
    public Date getWorkDte() {
        return this.workDte;
    }
    
    public void setWorkDte(Date workDte) {
        this.workDte = workDte;
    }

    
    @Column(name="CORP_COD", nullable=false, length=12)
    public String getCorpCod() {
        return this.corpCod;
    }
    
    public void setCorpCod(String corpCod) {
        this.corpCod = corpCod;
    }

    
    @Column(name="DEPT_COD", nullable=false, length=12)
    public String getDeptCod() {
        return this.deptCod;
    }
    
    public void setDeptCod(String deptCod) {
        this.deptCod = deptCod;
    }

    
    @Column(name="BUSINESS", length=200)
    public String getBusiness() {
        return this.business;
    }
    
    public void setBusiness(String business) {
        this.business = business;
    }

    
    @Column(name="GRADE_SCH", length=50)
    public String getGradeSch() {
        return this.gradeSch;
    }
    
    public void setGradeSch(String gradeSch) {
        this.gradeSch = gradeSch;
    }

    
    @Column(name="SPECIALITY", length=50)
    public String getSpeciality() {
        return this.speciality;
    }
    
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    
    @Column(name="HOME_TOWN", length=100)
    public String getHomeTown() {
        return this.homeTown;
    }
    
    public void setHomeTown(String homeTown) {
        this.homeTown = homeTown;
    }

    
    @Column(name="BIRTH_PLAC", length=100)
    public String getBirthPlac() {
        return this.birthPlac;
    }
    
    public void setBirthPlac(String birthPlac) {
        this.birthPlac = birthPlac;
    }

    
    @Column(name="TO_PORT_TIM", length=7)
    public Date getToPortTim() {
        return this.toPortTim;
    }
    
    public void setToPortTim(Date toPortTim) {
        this.toPortTim = toPortTim;
    }

    
    @Column(name="WAGE_NUM", precision=10)
    public Double getWageNum() {
        return this.wageNum;
    }
    
    public void setWageNum(Double wageNum) {
        this.wageNum = wageNum;
    }

    
    @Column(name="HEALTH", length=20)
    public String getHealth() {
        return this.health;
    }
    
    public void setHealth(String health) {
        this.health = health;
    }

    
    @Column(name="PHONE", length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="NOTE", length=100)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="WAGE_BASE", precision=10)
    public Double getWageBase() {
        return this.wageBase;
    }
    
    public void setWageBase(Double wageBase) {
        this.wageBase = wageBase;
    }

    
    @Column(name="SERVICE_NUM", precision=2, scale=0)
    public Byte getServiceNum() {
        return this.serviceNum;
    }
    
    public void setServiceNum(Byte serviceNum) {
        this.serviceNum = serviceNum;
    }

    
    @Column(name="CONTRIB_VAL", precision=3, scale=1)
    public Double getContribVal() {
        return this.contribVal;
    }
    
    public void setContribVal(Double contribVal) {
        this.contribVal = contribVal;
    }

    @Transient
    private Integer flag;

    @Formula("(select count(t.car_no) from WORKER_CAR t where t.worker_cod(+) = WORKER_COD)")
    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    @Transient
    private String corpNam;
    @Transient
    private String deptNam;

    @Formula("(select t.corp_nam from C_CORP t where t.corp_cod = CORP_COD)")
    public String getCorpNam() {
        return corpNam;
    }

    public void setCorpNam(String corpNam) {
        this.corpNam = corpNam;
    }

    @Formula("(select t.dept_nam from C_DEPT t where t.dept_cod = DEPT_COD)")
    public String getDeptNam() {
        return deptNam;
    }

    public void setDeptNam(String deptNam) {
        this.deptNam = deptNam;
    }
}


